include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BegoneCIAFlipswitch
$(BUNDLE_NAME)_FILES = Switch.xm
$(BUNDLE_NAME)_FRAMEWORKS = UIKit
$(BUNDLE_NAME)_LIBRARIES = flipswitch
$(BUNDLE_NAME)_INSTALL_PATH = /Library/Switches
$(BUNDLE_NAME)_EXTRA_FRAMEWORKS += Cephei

include $(THEOS_MAKE_PATH)/bundle.mk
